### ISSUE TITLE
C++でGrepを実装

### ISSUE THREAD

**Issue by Iso1127** [fukushimayst/task-c-2#1]
質問などはここに書いてください

**Comment by Iso1127** [comment]
質問などはここに書いてください

**Comment by fukushimayst** [comment]
磯西さん、
お疲れ様です。　福島です。
ご連絡、ありがとうございます。
今後は、質問事項は、こちらのメールあてに書かせていただきます。

早速質問なのですが、課題1で作成するプログラムの方向性としては、
Ubuntu上に打ち込んだ文字列をコード上で読み取り、
さらにコード上で検索対象のファイルを読み込み、指定文字列が
あるかを検索し、結果を表示するようなプログラムを作成するという
認識でよいでしょうか？

以上です。　よろしくお願いいたします。

**Comment by Iso1127** [comment]
はい。その認識であっています。
オプション設定(-r など)はひとまず置いておいて、Ubuntu上の動作と同じ動いをするように
実装してみてください。

**Comment by fukushimayst** [comment]
磯西さん、お疲れ様です。　福島です。
ご連絡が遅くなり、申し訳ありません。

先ほど、Ubuntu上から、このリモートリポジトリの"https://github.com/fukushimayst/task-c-2.git"に対し、pushし、"Everything up-to-date"と表示されたので、pushできたかなと思っているのですが、ファイルを見ることができるか、確認していただけますでしょうか。　　以上です。

**Comment by fukushimayst** [comment]
この後、進捗報告にも書きますが、課題1のビルドは、問題なく実行できたかなと考えております。　ただ、コマンドライン引数の使い方というか、引数指定がよく理解できていないため、想定通りの課題1の実行はできておりません。　以上です。

**Comment by fukushimayst** [comment]
先ほど、メール上で書いたことを、ここにも書いておきます。

磯西さん、
お疲れ様です。　福島です。
ご連絡が遅くなり、申し訳ありませんでした。

進捗報告について、メールで報告する
という件につきまして、承知いたしました。

また、金曜の進捗報告が分かりにくく
なっており、申し訳ありませんでした。

進捗等の確認につきまして、この後
2dc1のzoomのミーティング予定を
設定したほうがよいでしょうか。
　→福島個人のzoomミーティングに
　　入っていただく形でもよいです。

以上です。　よろしくお願いいたします。

**Comment by Iso1127** [comment]
ミーティング設定お願いします。
私の番号にSMS で連絡ください。

**Comment by Iso1127** [comment]
masterにコードがアップされてることは確認しました。

**Comment by Iso1127** [comment]
今のところ大丈夫てすが、
ここは公開サイトなのでその辺気をつけてください。

**Comment by fukushimayst** [comment]
ミーティングを設定するので、少々お待ちください。
設定でき次第、その情報を、磯西さんのSMSあてに送るという認識で大丈夫でしょうか。

また、コード確認、ありがとうございます。
今後は、githubが公開サイトであることをもっと意識して、
載せるべきか迷った場合は、載せないように注意します。

**Comment by Iso1127** [comment]
Branch名は、kadai1　でお願いします。

**Comment by fukushimayst** [comment]
github上に、新たなブランチ"kadai1"を追加して、そこにローカル上で変更した内容をpushする、という認識で合ってますか。

**Comment by Iso1127** [comment]
はい

**Comment by fukushimayst** [comment]
承知いたしました。

**Comment by fukushimayst** [comment]
お疲れ様です。　福島です。
先ほどkadai1のブランチにpushしたので、ご確認、お願いいたします。
ただ、変更分はほとんどありません。　Ubuntu上で、$ grep イタリア *のように入力すると、"country.txt"内の、該当する一行が表示されはするのですが、その国はAに所属している、その国はどこにも所属していない、などのこちらが指定した文字列を、grep検索のコマンドを打った際に、どのようにすれば表示できるかを調べたのですが、結果的に分からなかったからです。　
また、push時に"git push https://github.com/fukushimayst/task-c-2.git task-c-grep-local:kadai1" とコマンドを打ったのですが、こちらで問題ないでしょうか。　github上のkadai1にのみ、pushされていたので、個人的にはこれで良いのかなと思っているのですが、、。　以上です。

**Comment by Iso1127** [comment]
内容確認しました。
特に大きな問題はないとは思います。

Git のコマンドはよくはないですが、いったんこれでよいてす。

**Comment by fukushimayst** [comment]
承知しました。　ありがとうございます。
